version: '3.8'

services:
  app:
    build: .
    container_name: backend-app
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db             
      - DB_USER=root           
      - DB_PASSWORD=223142   
      - DB_NAME=myapp         
      - DB_PORT=3306           
      - JWT_SECRET=supersecretkey
    depends_on:
      - db                     
  
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 223142
      MYSQL_DATABASE: myapp           
    ports:
      - "3307:3306"   
    volumes:
      - mysql_data:/var/lib/mysql      

volumes:
  mysql_data:
